version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "vendor:"
    open-pull-requests-limit: 3
    rebase-strategy: disabled
    labels:
      - enhancement
      - vendor
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    labels:
      - ci
      - enhancement
